modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/thereallemon/llm-conversations/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"
displayURL="https://github.com/thereallemon/llm-conversations"

[[dependencies.llmconversations]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.llmconversations]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.llmconversations]]
    modId="minecolonies"
    type="required"
    versionRange="[1.1,)"
    ordering="AFTER"
    side="BOTH"
